using System;

namespace Dangl.OpenCDE.Shared
{
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionsService
    {
        public static string Version => "0.1.1-beta0015";
        public static string CommitInfo => "Branch.develop.Sha.1b6e9e38ffb7abd3817abcf6ec63f8bda4251f24";
        public static string CommitDate => "2021-08-26";
        public static string CommitHash => "1b6e9e38ffb7abd3817abcf6ec63f8bda4251f24";
        public static string InformationalVersion => "0.1.1-beta.15+Branch.develop.Sha.1b6e9e38ffb7abd3817abcf6ec63f8bda4251f24";
        public static DateTime BuildDateUtc { get; } = new DateTime(2021, 8, 26, 21, 34, 54, DateTimeKind.Utc);
    }
}
