using System;

namespace Dangl.OpenCDE.Shared
{
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionsService
    {
        public static string Version => "0.1.1-beta0012";
        public static string CommitInfo => "Branch.develop.Sha.63cf4980cce0fe1e9e9748a20aa1031c679eca6e";
        public static string CommitDate => "2021-08-26";
        public static string CommitHash => "63cf4980cce0fe1e9e9748a20aa1031c679eca6e";
        public static string InformationalVersion => "0.1.1-beta.12+Branch.develop.Sha.63cf4980cce0fe1e9e9748a20aa1031c679eca6e";
        public static DateTime BuildDateUtc { get; } = new DateTime(2021, 8, 26, 8, 55, 31, DateTimeKind.Utc);
    }
}