/*
 * OpenCDE Documents API
 *
 * OpenCDE Documents API Specification
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Dangl.OpenCDE.Shared.OpenCdeSwaggerGenerated.Converters;

namespace Dangl.OpenCDE.Shared.OpenCdeSwaggerGenerated.Models
{ 
    /// <summary>
    /// A specification for the request sequence required to upload a document to the CDE
    /// </summary>
    [DataContract]
    public partial class DocumentToUpload : IEquatable<DocumentToUpload>
    {
        /// <summary>
        /// A client-provided identifier that allows matching the specification with the correct file on the user&#39;s machine
        /// </summary>
        /// <value>A client-provided identifier that allows matching the specification with the correct file on the user&#39;s machine</value>
        [Required]
        [MinLength(1)]
        [DataMember(Name="session_file_id", EmitDefaultValue=false)]
        public string SessionFileId { get; set; }

        /// <summary>
        /// An array of request specifications detailing how to split the file to parts and upload each part to the CDE
        /// </summary>
        /// <value>An array of request specifications detailing how to split the file to parts and upload each part to the CDE</value>
        [Required]
        [DataMember(Name="upload_file_parts", EmitDefaultValue=false)]
        public List<UploadFilePartInstruction> UploadFileParts { get; set; }

        /// <summary>
        /// Gets or Sets UploadCompletion
        /// </summary>
        [Required]
        [DataMember(Name="upload_completion", EmitDefaultValue=false)]
        public LinkData UploadCompletion { get; set; }

        /// <summary>
        /// Gets or Sets UploadCancellation
        /// </summary>
        [Required]
        [DataMember(Name="upload_cancellation", EmitDefaultValue=false)]
        public LinkData UploadCancellation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocumentToUpload {\n");
            sb.Append("  SessionFileId: ").Append(SessionFileId).Append("\n");
            sb.Append("  UploadFileParts: ").Append(UploadFileParts).Append("\n");
            sb.Append("  UploadCompletion: ").Append(UploadCompletion).Append("\n");
            sb.Append("  UploadCancellation: ").Append(UploadCancellation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DocumentToUpload)obj);
        }

        /// <summary>
        /// Returns true if DocumentToUpload instances are equal
        /// </summary>
        /// <param name="other">Instance of DocumentToUpload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocumentToUpload other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    SessionFileId == other.SessionFileId ||
                    SessionFileId != null &&
                    SessionFileId.Equals(other.SessionFileId)
                ) && 
                (
                    UploadFileParts == other.UploadFileParts ||
                    UploadFileParts != null &&
                    other.UploadFileParts != null &&
                    UploadFileParts.SequenceEqual(other.UploadFileParts)
                ) && 
                (
                    UploadCompletion == other.UploadCompletion ||
                    UploadCompletion != null &&
                    UploadCompletion.Equals(other.UploadCompletion)
                ) && 
                (
                    UploadCancellation == other.UploadCancellation ||
                    UploadCancellation != null &&
                    UploadCancellation.Equals(other.UploadCancellation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (SessionFileId != null)
                    hashCode = hashCode * 59 + SessionFileId.GetHashCode();
                    if (UploadFileParts != null)
                    hashCode = hashCode * 59 + UploadFileParts.GetHashCode();
                    if (UploadCompletion != null)
                    hashCode = hashCode * 59 + UploadCompletion.GetHashCode();
                    if (UploadCancellation != null)
                    hashCode = hashCode * 59 + UploadCancellation.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DocumentToUpload left, DocumentToUpload right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DocumentToUpload left, DocumentToUpload right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
