/*
 * OpenCDE Documents API
 *
 * OpenCDE Documents API Specification
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Dangl.OpenCDE.Shared.OpenCdeSwaggerGenerated.Converters;

namespace Dangl.OpenCDE.Shared.OpenCdeSwaggerGenerated.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DocumentUploadSessionInitialization : IEquatable<DocumentUploadSessionInitialization>
    {
        /// <summary>
        /// A CDE UI URL for the client to open in a local browser. The user would enter document metadata directly in the CDE
        /// </summary>
        /// <value>A CDE UI URL for the client to open in a local browser. The user would enter document metadata directly in the CDE</value>
        [Required]
        [MinLength(1)]
        [DataMember(Name="upload_ui_url", EmitDefaultValue=false)]
        public string UploadUiUrl { get; set; }

        /// <summary>
        /// &#x60;upload_ui_url&#x60; expiry in seconds
        /// </summary>
        /// <value>&#x60;upload_ui_url&#x60; expiry in seconds</value>
        [Required]
        [DataMember(Name="expires_in", EmitDefaultValue=true)]
        public int ExpiresIn { get; set; }

        /// <summary>
        /// The maximum file size supported by the CDE. Attempts to upload a larger file will fail
        /// </summary>
        /// <value>The maximum file size supported by the CDE. Attempts to upload a larger file will fail</value>
        [Required]
        [DataMember(Name="max_size_in_bytes", EmitDefaultValue=true)]
        public long MaxSizeInBytes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocumentUploadSessionInitialization {\n");
            sb.Append("  UploadUiUrl: ").Append(UploadUiUrl).Append("\n");
            sb.Append("  ExpiresIn: ").Append(ExpiresIn).Append("\n");
            sb.Append("  MaxSizeInBytes: ").Append(MaxSizeInBytes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DocumentUploadSessionInitialization)obj);
        }

        /// <summary>
        /// Returns true if DocumentUploadSessionInitialization instances are equal
        /// </summary>
        /// <param name="other">Instance of DocumentUploadSessionInitialization to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocumentUploadSessionInitialization other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    UploadUiUrl == other.UploadUiUrl ||
                    UploadUiUrl != null &&
                    UploadUiUrl.Equals(other.UploadUiUrl)
                ) && 
                (
                    ExpiresIn == other.ExpiresIn ||
                    
                    ExpiresIn.Equals(other.ExpiresIn)
                ) && 
                (
                    MaxSizeInBytes == other.MaxSizeInBytes ||
                    
                    MaxSizeInBytes.Equals(other.MaxSizeInBytes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (UploadUiUrl != null)
                    hashCode = hashCode * 59 + UploadUiUrl.GetHashCode();
                    
                    hashCode = hashCode * 59 + ExpiresIn.GetHashCode();
                    
                    hashCode = hashCode * 59 + MaxSizeInBytes.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DocumentUploadSessionInitialization left, DocumentUploadSessionInitialization right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DocumentUploadSessionInitialization left, DocumentUploadSessionInitialization right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
