// This file is automatically generated as part of the build process

export const version = {
    version: "0.1.1-beta0028",
    commitInfo: "Branch.develop.Sha.94abfb7bb21fceb98b489d69b74974e25d2637c6",
    commitDate: "2021-08-27",
    commitHash: "94abfb7bb21fceb98b489d69b74974e25d2637c6",
    informationalVersion: "0.1.1-beta.28+Branch.develop.Sha.94abfb7bb21fceb98b489d69b74974e25d2637c6",
    buildDateUtc: new Date(Date.UTC(2021, 7, 27, 13, 51, 24))
}